# Generated by Django 4.2.20 on 2025-12-24 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_overviews', '0029_alter_historicalcourseoverview_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseoverview',
            name='proctoring_event_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalcourseoverview',
            name='proctoring_event_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
